// Generated by Selenium IDE e corrigido manualmente
const { Builder, By, Key, until } = require('selenium-webdriver')
const chrome = require('selenium-webdriver/chrome') // Configura as opções do Chrome
const assert = require('assert')

describe('SIG', function() {
  this.timeout(30000)
  let driver
  let vars

  beforeEach(async function() {
    // Configurações para corrigir o erro de Sandbox e permissões no Windows
    let options = new chrome.Options()
    options.addArguments('--no-sandbox')
    options.addArguments('--disable-dev-shm-usage')
    options.addArguments('--remote-allow-origins=*')

    driver = await new Builder()
      .forBrowser('chrome')
      .setChromeOptions(options) // Aplica as opções ao navegador
      .build()
    vars = {}
  })

  afterEach(async function() {
    await driver.quit();
  })

  it('SIG', async function() {
    await driver.get("https://www.terraplanner.org/")
    await driver.manage().window().setRect({ width: 1258, height: 946 })
    await driver.findElement(By.name("search")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.name("search")).sendKeys("Praça Tiradentes, MG Ouro preto")
    await driver.findElement(By.css(".sc-ehixzo:nth-child(2) > svg")).click()
    
    // ESPERA EXPLICÍTA: Aguarda até 10 segundos para o mapa aparecer na tela antes de prosseguir
    await driver.wait(until.elementLocated(By.css(".ol-layer > canvas")), 10000);

    {
      const element = await driver.findElement(By.css(".sc-ehixzo:nth-child(2)"))
      await driver.actions({ bridge: true }).move({ origin: element }).perform()
    }
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).move({ origin: element }).press().perform()
    }
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).move({ origin: element }).perform()
    }
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).release().perform()
    }
    await driver.findElement(By.css(".ol-layer > canvas")).click()
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).move({ origin: element }).press().perform()
    }
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).move({ origin: element }).perform()
    }
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).release().perform()
    }
    await driver.findElement(By.css(".ol-layer > canvas")).click()
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).move({ origin: element }).press().perform()
    }
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).move({ origin: element }).perform()
    }
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).release().perform()
    }
    await driver.findElement(By.css(".ol-layer > canvas")).click()
    await driver.findElement(By.css(".ol-layer > canvas")).click()
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).move({ origin: element }).press().perform()
    }
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).move({ origin: element }).perform()
    }
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).release().perform()
    }
    await driver.findElement(By.css(".ol-layer > canvas")).click()
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).move({ origin: element }).press().perform()
    }
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).move({ origin: element }).perform()
    }
    {
      const element = await driver.findElement(By.css(".ol-layer > canvas"))
      await driver.actions({ bridge: true }).release().perform()
    }
    await driver.findElement(By.css(".ol-layer > canvas")).click()
    await driver.findElement(By.css(".ol-layer > canvas")).click()
  })
})